all:
	#g++ -g -std=c++0x *.cpp -o asfer
	#g++ -g -w -std=c++14 *.cpp -o asfer
	#g++ -g -w -std=c++14 -I/usr/include/python2.7 -L/usr/lib/i386-linux-gnu  remove_duplicates.cpp -lpython2.7 -o remove_duplicates 
	#g++ -g -w -std=c++11  placement_new.cpp -o placement_new 
	g++-4.8 -g -w -std=c++11 unordered_map_auto_iter.cpp -o unordered_map_auto_iter
clean:
	rm remove_duplicates 

