
verhulstpearlreedlaw <- function(filename, lambdaVPR, lambdaMay, initialcondition, scalemult)
{
  print(filename)
  layout(matrix(1:3,3,1))
  coronavirus2019dataset <- read.table(filename, header=TRUE)
  #print(coronavirus2019dataset[[2]])
  covid2019df <- data.frame(as.numeric(coronavirus2019dataset[[2]]))
  attach(covid2019df)
  coronavirus2019scaled <- c(as.double(coronavirus2019dataset[[2]]))
  coronavirus2019scaled <- coronavirus2019scaled/max(coronavirus2019scaled)
  #coronavirus2019scaled <- covid2019df[[1]]/max(covid2019df[[1]])
  print("coronavirus2019scaled:")
  print(coronavirus2019scaled)
  covid2019ts <- ts(coronavirus2019scaled)
  ts.plot(covid2019ts)
  vprlogistic <- c()
  maylogistic <- c()
  x1 <- as.double(initialcondition)
  x2 <- as.double(initialcondition)
  for(n in 1:length(coronavirus2019scaled))
  {
    scalingmultiplicand <- scalemult 
    x1next <- as.double(lambdaVPR * x1 * (1 - x1))
    vprlogistic <- c(vprlogistic, x1next)
    x2next <- as.double(x2 * exp(lambdaMay * (1 - x2)))
    maylogistic <- c(maylogistic, x2next)
    x1 <- x1next * scalingmultiplicand
    x2 <- x2next * scalingmultiplicand
  }
  print("---------------------------------------------")
  print("Verhulste-Pearl-Reed logistic:")
  print("---------------------------------------------")
  print(rev(vprlogistic))
  corrcoeff11_test <- cor.test(coronavirus2019scaled,rev(vprlogistic),method="kendall",alternative="greater")
  corrcoeff11 <- cor(coronavirus2019scaled,rev(vprlogistic),method="kendall")
  print("Kendall correlation coefficient:")
  print(corrcoeff11_test)
  print(corrcoeff11)
  corrcoeff12_test <- cor.test(coronavirus2019scaled,rev(vprlogistic),method="spearman",alternative="greater")
  corrcoeff12 <- cor(coronavirus2019scaled,rev(vprlogistic),method="spearman")
  print("Spearman correlation coefficient:")
  print(corrcoeff12_test)
  print(corrcoeff12)
  corrcoeff13_test <- cor.test(coronavirus2019scaled,rev(vprlogistic),method="pearson",alternative="greater")
  corrcoeff13 <- cor(coronavirus2019scaled,rev(vprlogistic),method="pearson")
  print("Pearson correlation coefficient:")
  print(corrcoeff13_test)
  print(corrcoeff13)
  vprlogisticts <- ts(rev(vprlogistic))
  ts.plot(vprlogisticts)
  print("---------------------------------------------")
  print("Robert May logistic:")
  print("---------------------------------------------")
  print(rev(maylogistic))
  corrcoeff21_test <- cor.test(coronavirus2019scaled,rev(maylogistic),method="kendall",alternative="greater")
  corrcoeff21 <- cor(coronavirus2019scaled,rev(maylogistic),method="kendall")
  print("Kendall correlation coefficient:")
  print(corrcoeff21_test)
  print(corrcoeff21)
  corrcoeff22_test <- cor.test(coronavirus2019scaled,rev(maylogistic),method="spearman",alternative="greater")
  corrcoeff22 <- cor(coronavirus2019scaled,rev(maylogistic),method="spearman")
  print("Spearman correlation coefficient:")
  print(corrcoeff22_test)
  print(corrcoeff22)
  corrcoeff23_test <- cor.test(coronavirus2019scaled,rev(maylogistic),method="pearson",alternative="greater")
  corrcoeff23 <- cor(coronavirus2019scaled,rev(maylogistic),method="pearson")
  print("Pearson correlation coefficient:")
  print(corrcoeff23_test)
  print(corrcoeff23)
  maylogisticts <- ts(rev(maylogistic))
  ts.plot(maylogisticts)
  print("---------------------------------------------")
  print("vprlogistic factors:")
  print("---------------------------------------------")
  print(factor(vprlogistic))
  print("---------------------------------------------")
  print("maylogistic factors:")
  print("---------------------------------------------")
  print(factor(maylogistic))
  c(corrcoeff11,corrcoeff12,corrcoeff13,corrcoeff21,corrcoeff22,corrcoeff23)
}
#corcoeff <- verhulstpearlreedlaw("./VerhulstPearlReedLogistic.dat",4.829487535509905,0.00000000000001)
#corcoeff <- verhulstpearlreedlaw("./VerhulstPearlReedLogistic.dat",0.529487535509905,0.00000000000001)
#corcoeff <- verhulstpearlreedlaw("./VerhulstPearlReedLogistic.dat",1.079487535509905,0.00000000000001)
corcoeff <- verhulstpearlreedlaw("./VerhulstPearlReedLogistic.dat",0.35201,0.35,0.00000000000001,3.0)
#corcoeff <- verhulstpearlreedlaw("./VerhulstPearlReedLogistic.dat",1.129487535509905,0.00000000000001)
#corcoeff <- verhulstpearlreedlaw("./VerhulstPearlReedLogistic.dat",2.529487535509905,0.00000000000001)
#corcoeff <- verhulstpearlreedlaw("./VerhulstPearlReedLogistic.dat",2.479487535509905,0.00000000000001)
print("correlation coefficients:")
print(corcoeff)
